### ISSUE TITLE
Idea for a Classic Theme version of Basic Themer

### ISSUE THREAD

**Issue by tehjxnm** [Ingan121/BasicThemer2#20] opened 2022-07-15 17:47 UTC
A little idea that came to my mind. I thought of a simpler, one click way to replace the Windows 11 design with something more familiar to older versions of Windows (95, 98, 2000). I don't like how Windows 11 looks and I want to revert back to that "blocky", but memorable design. 

Should also have an option to change the look of the Windows, something like this.
![image](https://user-images.githubusercontent.com/91823966/179281793-3da73944-090e-43b4-9656-e2e2183b221f.png)

I can't find the exact image of what I'm talking about, but you probably get the idea. I hope you can do it! Cheers.

- Jexx

**Comment by gdl-blue** [comment] 2022-07-16 13:37
Copy desk.cpl, comctl32.dll from Windows 2000 and open desk.cpl on HxD or Notepad++ and replace all comctl32.dll to comctlxp.dll, rename comctl32.dll file to comctlxp.dll, rename desk.cpl to something else(like deskn.cpl) and open it, go to appearence tab. Note that this will (instantly or not) change Padded Border Width to 0 so you'll need to modify the registry.

**Comment by tehjxnm** [comment] 2022-07-17 14:08
BasicThemer2 let's me apply the Basic look without administration (of course everytime I open up BasicThener it's a bit annoying that a popup saying that I need administration privileges, but clicking "no" also gives you the disabled DWM look). I am on an account that has no administration. I don't think your solution may work out.

**Comment by OrthodoxWindows** [comment] 2022-07-17 14:42
There are already solutions to apply the classic theme in Windows 8-10-11 :

https://winclassic.boards.net/thread/510/classicthemetray-quickly-toggle-classic-theme?page=1&scrollTo=3720
https://github.com/spitfirex86/ClassicThemeTray
https://winclassic.boards.net/thread/456/simple-classic-theme-supports-windows
https://winclassic.boards.net/thread/43/windows-classic-theme-task-scheduler
https://winclassic.boards.net/thread/990/windows-classic-theme-on-1903
https://github.com/valinet/ExplorerPatcher/discussions/167

However, all these solutions require administrator privileges. There is currently no workaround for this. This exists in draft form, but it seems far from being realized : https://winclassic.boards.net/thread/456/simple-classic-theme-supports-windows?page=32

As for simply switching from one theme to another, you can use my scripts (which require BasicThemer2 and ClassicThemeTray) :
https://github.com/OrthodoxWindows/ThemeSwitcherScripts

More generally, you can't get very far in customizing Windows without administrative privileges.

**Comment by tehjxnm** [comment] 2022-07-17 18:06
I guess you're right, but that may be the best solution. I will look around if I have time. Thanks so much.

**Comment by tehjxnm** [comment] 2022-07-17 18:13
I've noticed that it contains malware, is harmful to my computer?

**Comment by OrthodoxWindows** [comment] 2022-07-17 19:02
This is a false positive. This comes from the way of activating the classic theme, by intervening on the management of the theme of the system (by closing the handle of the visual style). **As a result, all classic theme activation tools are detected by antivirus.**

**Comment by tehjxnm** [comment] 2022-07-17 19:41
So what you're trying to say is that ClassicThemeTray is using a different .net API? That seems understandable. How do I get it then? And is it possible to disable the antivirus without UAC? I use Windows Defender.

**Comment by OrthodoxWindows** [comment] 2022-07-17 21:19
No, ClassicThemeTray does not use a custom .NET API. The problem is in how to get the classic theme. To do this, DWM must be forced to draw the classic theme by closing access to the theme service (which provides the .msstyle visual style). This is suspicious activity for antiviruses.

To add a permanent exception to Windows Defender, I advise you to use this tool: https://www.sordum.org/10636/defender-exclusion-tool-v1-3/

**Comment by tehjxnm** [comment] 2022-07-23 13:39
Does this work without administration? If not, then I don't know what do I do then

**Comment by OrthodoxWindows** [comment] 2022-07-23 14:12
Unfortunately no. Current tools to activate the classic theme do not work without administration. The only exception is MCT, but I have absolutely no idea when the project will be finalized. If you wish, you can register on the WinClassic forum to request information from the project developer (SimpleClassicTHeme and MCT). https://winclassic.boards.net/thread/456/simple-classic-theme-supports-windows?page=32

**Comment by Ingan121** [comment] 2022-08-29 15:42
> BasicThemer2 let's me apply the Basic look without administration (of course everytime I open up BasicThener it's a bit annoying that a popup saying that I need administration privileges, but clicking "no" also gives you the disabled DWM look). I am on an account that has no administration. I don't think your solution may work out.

You can launch BT2 without the prompt with /noadminalert command line argument. I'm currently thinking of removing the annoying admin prompt and making BT2 always run as admin, also providing a shortcut for running without admin.

Regarding the classic theming feature, it is out of scope for this project and I'm not going to implement it anytime soon. Please consider the alternatives given by other users above.

**Closed as completed by Ingan121** 2022-08-29 15:42 UTC
